services:
    stsbl.exam_plan_unlock.unlock:
        class: Stsbl\ExamPlanUnlockBundle\Service\Unlock
        arguments: ["@iserv.shell", "@iserv.security_handler", "@iserv.config", "@request_stack"]
    
    stsbl.exam_plan_unlock.menu:
        class: Stsbl\ExamPlanUnlockBundle\EventListener\MenuSubscriber # Out MenuSubscriber Class
        tags:
            - { name: kernel.event_subscriber } # Tells IServ about our subsriber
            
    stsbl.exam_plan_unlock.security.unlock_voter:
        class: Stsbl\ExamPlanUnlockBundle\Security\Authorization\Voter\UnlockVoter
        arguments: ["@security.access.decision_manager", "@doctrine.orm.entity_manager"]
        public: false
        tags:
            - { name: security.voter }