services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\ExamPlanUnlockBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Model,Resources,Tests}/*'

    Stsbl\ExamPlanUnlockBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']